name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build
      working-directory: build
      run: |
        ./build
        JCFLAGS="--release 6" AUTHTS="$(git log -1 --format=%at)" ./build

  build-with-jdk8:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: setup env
      run: |
        JAVA_HOME="${JAVA_HOME_8_X64}"
        echo "${JAVA_HOME_8_X64}/bin:$(cat $GITHUB_PATH)" > "$GITHUB_PATH"
    - name: build
      working-directory: build
      run: |
        BUILD_NIO_CLIENTS=0 JCFLAGS="-source 1.5 -target 1.5" AUTHTS="$(git log -1 --format=%at)" ./build
