name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build
      working-directory: build
      run: |
        ./build
        JCFLAGS="--release 6" AUTHTS="$(git log -1 --format=%at)" ./build

  build-with-jdk8:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: build
      working-directory: build
      run: |
        JAVA_HOME="${JAVA_HOME_8_X64}"
        echo "${JAVA_HOME_8_X64}/bin:$(cat $GITHUB_PATH)" > "$GITHUB_PATH"
        echo "$JAVA_HOME"
        javac -version
        javadoc -version
        JCFLAGS="--release 6" AUTHTS="$(git log -1 --format=%at)" ./build
        JCFLAGS="-source 1.5 -target 1.5" ./build
